✨Add botinfo command
ZumitoTeam/zumito-bot pull request #71
Opened 2022-10-16 21:13 UTC by WilliamAcosta1

# Description
Basic command to view the bot status

# Test

## Set of tests

| Use case | Result |
| :------- | :----- |
| zb-botinfo | 
![image](https://user-images.githubusercontent.com/105233030/196058576-63a23879-304f-4d64-a450-d1ba855ca969.png)
 |

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added the corresponding tranaslations at least in english language
- [ ] I checked my command works properly using prefix and slash commands

2023-04-22 08:49 UTC, fernandomema requested changes

2023-04-22 08:49 UTC, fernandomema commented on src/modules/info/commands/botstats.ts
> +export class Botstats extends Command {
Utiliza UpperCamelCase por favor. BotStatus

2023-04-22 08:49 UTC, fernandomema commented on src/modules/info/commands/botstats.ts
> +    examples: string[] = [];
No borres el ejemplo vacío. Este se utiliza para crear un ejemplo sin parámetros.

2023-04-22 15:53 UTC, WilliamAcosta1 commented on src/modules/info/commands/botstats.ts
> +export class Botstats extends Command {
Alr

2023-04-22 15:53 UTC, WilliamAcosta1 commented on src/modules/info/commands/botstats.ts
> +    examples: string[] = [];
Alr

2023-04-23 16:02 UTC, fernandomema approved these changes

2023-04-23 16:03 UTC, merged